# Ex1 - Filtering and Sorting Data

This time we are going to pull data directly from the internet.
Special thanks to: https://github.com/justmarkham for sharing the dataset and materials.

### Step 1. Import the necessary libraries

In [1]:
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv).

### Step 3. Assign it to a variable called chipo.

In [2]:
chipo = pd.read_csv('https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv', sep='\t')

### Step 4. How many products cost more than $10.00?

In [21]:
chipo_filtered = chipo.drop_duplicates(['item_name', 'quantity', 'choice_description'])
chipo_one_prod = chipo_filtered[chipo_filtered.quantity == 1]

chipo.query('item_price > 10').item_name.nunique()

31

### Step 5. What is the price of each item? 
###### print a data frame with only two columns item_name and item_price

In [22]:
chipo.query('item_price > 10')

,order_id,quantity,item_name,choice_description,item_price
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98
5,3,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",10.98
7,4,1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",11.75
13,7,1,Chicken Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.25
23,12,1,Chicken Burrito,"[[Tomatillo-Green Chili Salsa (Medium), Tomati...",10.98
...,...,...,...,...,...
4610,1830,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",11.75
4611,1830,1,Veggie Burrito,"[Tomatillo Green Chili Salsa, [Rice, Fajita Ve...",11.25
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",11.25

### Step 6. Sort by the name of the item

In [23]:
chipo.query('item_price > 10').sort_values('item_name')

,order_id,quantity,item_name,choice_description,item_price
3389,1360,2,6 Pack Soft Drink,[Diet Coke],12.98
1643,664,1,Barbacoa Bowl,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",11.75
919,380,1,Barbacoa Bowl,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",11.75
3547,1426,1,Barbacoa Bowl,"[Fresh Tomato Salsa, [Rice, Cheese, Sour Cream...",11.75
4510,1793,1,Barbacoa Bowl,[Guacamole],11.49
...,...,...,...,...,...
186,83,1,Veggie Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.25
295,128,1,Veggie Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",11.25
3889,1559,2,Veggie Soft Tacos,"[Fresh Tomato Salsa (Mild), [Black Beans, Rice...",16.98
738,304,1,Veggie Soft Tacos,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",11.25
1699,688,1,Veggie Soft Tacos,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.25

### Step 7. What was the quantity of the most expensive item ordered?

In [28]:
chipo.groupby(['item_name', 'item_price'])['quantity'].sum().reset_index().sort_values('item_price', ascending=False)

                        item_name  item_price  quantity
123  Chips and Fresh Tomato Salsa       44.25        15
51                  Carnitas Bowl       35.25         3
93                Chicken Burrito       35.00         8
200                Veggie Burrito       33.75         3
81                   Chicken Bowl       32.94         3
..                            ...         ...       ...
151                 Side of Chips        1.69        99
26                  Bottled Water        1.50       117
41              Canned Soft Drink        1.25       264
25                  Bottled Water        1.09        22
38                    Canned Soda        1.09        84

[209 rows x 3 columns]

### Step 8. How many times was a Veggie Salad Bowl ordered?

In [36]:
chipo.loc[chipo['item_name'] == 'Veggie Salad Bowl', :].count()

order_id              18
quantity              18
item_name             18
choice_description    18
item_price            18
dtype: int64

### Step 9. How many times did someone order more than one Canned Soda?

In [40]:
chipo.loc[(chipo['item_name'] == 'Canned Soda') & (chipo['quantity'] > 1), :].count()

order_id              20
quantity              20
item_name             20
choice_description    20
item_price            20
dtype: int64